name: sqlite_reporter
description: An sqlite plugin app for flutter_sqflite_manager
publish_to: none
# Paste just below 'description:'
version: 0.0.5

environment:
  sdk: ">=2.12.3 <3.0.0"
  flutter: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter
  sqlite_explorer:
    path: ../
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  tracers_package:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: tracers_package
  xfer:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: xfer
  after_layout: ^1.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.0.1
  flutter_modular: ^3.2.2+1
  intl: ^0.17.0
  moor: ^4.3.2
  moor_flutter: ^4.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner: ^2.0.4
  moor_generator: ^4.3.1
  test: ^1.17.7

flutter:
  uses-material-design: true
  assets:
    - data/activity_content.json
  
