name: example_developer
description: An example app for flutter_sqflite_manager
# Paste just below 'description:'

version: 0.0.3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  after_layout: ^1.0.7+2
  app_exception:
    git:
      url: https://github.com/GitHubStuff/app_exception.git
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  sqlite_explorer:
    path: ../
  hud_scaffold:
    git:
      url: https://github.com/GitHubStuff/hud_scaffold.git
  mode_theme:
    git:
      url: https://github.com/GitHubStuff/mode_theme.git
  shared_preferences: ^0.5.7+2
  sqlite_controller:
    git:
      url: https://github.com/GitHubStuff/sqlite_controller.git
  sqflite: ^1.3.0+1
  tracers:
    git:
      url: https://github.com/GitHubStuff/tracers.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
