name: example_developer
description: An example app for flutter_sqflite_manager
# Paste just below 'description:'

version: 0.0.4

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  after_layout: ^1.0.7+2
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  sqlite_explorer:
    path: ../
  hud_scaffold:
    path: ../hud_scaffold
  shared_preferences: ^0.5.7+2
  sqlite_controller:
    path: ../sqlite_controller
  sqflite: ^1.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
