name: sqlite_reporter
description: An sqlite plugin app for flutter_sqflite_manager
publish_to: none
version: 0.0.6+1

environment:
  sdk: ">=2.16.0 <3.0.0" #Dart SDK 2022-02-04
  flutter: ">=2.10.0"

dependencies:
  after_layout: ^1.1.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.4
  drift: ^1.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  flutter_modular: ^4.2.0
  intl: ^0.17.0
  path: ^1.8.0
  path_provider: ^2.0.2
  persisted_cache:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: persisted_cache
  shared_preferences: ^2.0.6
  sqflite: ^2.0.2
  sqlite3_flutter_libs: ^0.5.3
  sqlite_explorer:
    path: ../
  theme_management:
    git:
      url: https://github.com/RAE-Health/theme_management.git
  tracers_package:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: tracers_package
  xfer:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: xfer

dev_dependencies:
  build_runner: ^2.1.5
  drift_dev: ^1.0.2
  test: ^1.19.5

flutter:
  uses-material-design: true
  assets:
    - data/activity_content.json
