name: example_developer
description: An example app for flutter_sqflite_manager
publish_to: none
# Paste just below 'description:'
version: 0.0.4

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  sqlite_explorer:
    path: ../
  after_layout: ^1.1.0
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
