name: sqlite_explorer
description: Package to display sqlite data tables
publish_to: none
version: 0.8.1+2

environment:
  sdk: ">=2.13.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  json_decoder:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: json_decoder_package
  theme_manager:
    git:
      url: https://github.com/GitHubStuff/theme_manager.git
  after_layout: ^1.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  flutter_bloc: ^7.0.1
  flutter_modular: ^3.2.2+1
  moor: ^4.3.2
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3

dev_dependencies:
  build_runner: ^2.0.4
  moor_generator: ^4.3.1
  test: ^1.17.7

flutter:
  uses-material-design: true
