name: sqlite_explorer
description: Package to let developer display sqlite data tables
publish_to: none
version: 0.10.0+3

environment:
  sdk: ">=2.16.0 <3.0.0" #Dart SDK 2022-02-04
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  json_decoder:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: json_decoder_package
  persisted_cache:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: persisted_cache
  theme_manager:
    git:
      url: https://github.com/GitHubStuff/theme_manager.git
  after_layout: ^1.1.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.4
  dartz: ^0.10.0
  flutter_bloc: ^8.0.0
  flutter_modular: ^4.2.0
  drift: ^1.0.1
  path_provider: ^2.0.7
  shared_preferences: ^2.0.9
  sqlite3_flutter_libs: ^0.5.1

dev_dependencies:
  build_runner: ^2.1.5
  drift_dev: ^1.0.2
  test: ^1.17.9

flutter:
  uses-material-design: true
