name: sqlite_explorer
description: Package to display sqlite data tables
version: 0.3.1+3

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  after_layout: ^1.0.7+2
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  mode_theme:
    git:
      url: https://github.com/GitHubStuff/mode_theme.git
  shared_preferences: ^0.5.12+2
  sqlite_controller:
    git:
      url: https://github.com/GitHubStuff/sqlite_controller.git
  tracers:
    git:
      url: https://github.com/GitHubStuff/tracers.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
